### ISSUE TITLE
Implement relative path

### ISSUE THREAD

**Issue by MaximeBaudette** [SmarTS-Lab/iTesla_RaPId#17]
The toolbox should implement support for relative path. 
I think the default behavior should be to use relative path for model, FMU, and in and out data. This behaviour could be toggled off with a debug setting somewhere in the toolbox's advanced settings. 

A good thing would be to include this code in the toolbox:
http://www.mathworks.com/matlabcentral/fileexchange/41253-improved-relativepath-m

**Comment by janlav** [comment]
@MaximeBaudette can you expand on this topic and whether or not we already have taken care of this?

**Comment by MaximeBaudette** [comment]
My point is that for now when a user searchs for a path, it will import an absolute path into the container. 
This should be changed to be by default relative paths, with the container file's path as point of reference (for example). 
When run in debug mode, one could have only absolute paths. 
I guess we should implement a function "getpath" that implements all of this and use it everywhere

**Comment by janlav** [comment]
@MaximeBaudette if Matlab have (or we create) a function to check if a path is a part of another path we can do relative paths (relative to the container) for all cases when it is possible.

Would this be OK? Alternatives would be to remove absolute paths altogether or making a boolean which specifies if path is to be absolute or not. Let me know what you think.
@tinrabuzin @GiuseppeLaera @lvanfretti maybe you guys want to contribute as well?
