### ISSUE TITLE
Textbook example

### ISSUE THREAD

**Issue by tinrabuzin** [SmarTS-Lab/iTesla_RaPId#20]
The Rafael's textbook example should be fixed.

**Comment by lvanfretti** [comment]
@tinrabuzin can you make two versions of this? One that requires the GUI and another with CLI.

We should find a way to configure the RaPId set up file to run this automatically as part of the installation - it should help the user to get warnings and errors indicating their problems.

For example, if their arch is not supported, etc...

**Comment by tinrabuzin** [comment]
Yes, I'll do it.
