### ISSUE TITLE
Setup script cannot be run 

### ISSUE THREAD

**Issue by tinrabuzin** [SmarTS-Lab/iTesla_RaPId#41]
I get the following error message when I try to run the setup script. 

<img width="605" alt="screen shot 2016-03-28 at 18 26 51" src="https://cloud.githubusercontent.com/assets/13916934/14082876/bc9c9676-f512-11e5-8d56-4f7689c3679e.png">

BTW: Jan, that was after your last PR.

**Comment by janlav** [comment]
@tinrabuzin seems like there are to errors here, in order of increasing complexity:

- [ ] "tempfile" should be a string and not a variable (to save simulink-models with changes in them)

- [ ] in the test script we dont give the settings-struct a version-field which we would like to use to update old objects/structures - now it should work even without version-numbering!

Stand by for a PR please.
