### ISSUE TITLE
Remove Dependency on Image Processing Library

### ISSUE THREAD

**Issue by lvanfretti** [SmarTS-Lab/iTesla_RaPId#43]
When we implemented the first version of RaPId, I wanted to display the logo.
At that time (and still now) the only way that I knew how to do it was through some functions of the Image Processing library.

I think we can replace with the following function: http://se.mathworks.com/help/matlab/ref/imagesc.html

Otherwise, I guess there is not much point in keeping the image...

**Comment by janlav** [comment]
@lvanfretti you are correct that we don't need the image processing library - at present we are using `imshow() `which (from my understanding) actually is **not** part of the Image Processing lib. I think previous developers either used some other function or were deceived by the help text (the second part Examples use `imref2d()` of the Image Processing Toolbox but the first doesn't).

If no one disagrees I suggest that we just remove the Image Processing Toolbox from the dependencies list.

**Comment by tinrabuzin** [comment]
@janlav This dependancy list used to be created by the setup script. So, I guess there is another piece of code that uses Image Processing Toolbox if it appears in the list of dependancies generated by the script.

**Comment by janlav** [comment]
@tinrabuzin @lvanfretti turns out you guys was right, so I replaced `imshow()` with `image()` and `imread()` instead. Using (an improved) dependency check i now have eliminated the need for Image Processing Toolbox.

PR coming soon.
