### ISSUE TITLE
Adjustable timeout setting

### ISSUE THREAD

**Issue by tinrabuzin** [SmarTS-Lab/iTesla_RaPId#8]
Currently, if the simulation of the model runs longer than 1s, the whole simulation is discarded. I propose this setting is integrated so that the timeout can be adjusted.

**Comment by janlav** [comment]
Left to do is to implement a timeOut in rapid_ODEsolve, probably using a timer to generate errors in the try - catch statement wherein the command fmu.simulate() is given.

**Comment by janlav** [comment]
Fixed in db5390c
